### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by digitalsanctum** [awslabs/dynamodb-streams-kinesis-adapter#10]

**Comment by joelittlejohn** [comment]
I'd be interested to know if this project has any notional owner within Amazon. I think #7 is an important PR, because this project is now lagging far behind the KCL and can't coexist in a project with other libraries that need a later version of the KCL. In particular I think awslabs/amazon-kinesis-client#135 is an important fix and the DynamoDB Streams Kinesis Adapter really should depend on a version of the KCL that includes that fix.

It's disappointing to see that this project, which is discussed in detail in the DynamoDB Streams docs (and is still, to my knowledge, the best way to consume a DynamoDB stream in Java) is apparently dormant with no maintainers.

**Comment by amcp** [comment]
We updated the DynamoDB Streams Kinesis Adapter to be compatible with KCL 1.7.5.
